import { useEffect, useState } from "react";
// uploadReportDataUrl is the one used here: the photo is held as a data URL so
// an unsent report can carry it into the offline queue. uploadReportMedia (the
// raw-File path it delegates to) is not imported directly.
import { api, auth, enqueueOffline, flushOffline, getOfflineQueue, uploadReportDataUrl } from "@/lib/api";
import { Camera, MapPin, WifiHigh, WifiSlash, CloudArrowUp, ArrowLeft } from "@phosphor-icons/react";
import { Link, useNavigate } from "react-router-dom";

const TYPES=["LANDSLIDE","ROAD_BLOCKAGE","CRACK","SEEPAGE","SLOPE_MOVEMENT","ROCKFALL","OTHER"];
export default function FieldOfficer(){
 const nav=useNavigate(),[online,setOnline]=useState(navigator.onLine),[queueSize,setQueueSize]=useState(getOfflineQueue().length),[nearest,setNearest]=useState(null),[pos,setPos]=useState(null),[type,setType]=useState(TYPES[0]),[description,setDescription]=useState(""),[photo,setPhoto]=useState(null),[photoName,setPhotoName]=useState("evidence.jpg"),[submitting,setSubmitting]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{const on=()=>{setOnline(true);flushOffline().then(setQueueSize)},off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);if(navigator.onLine)flushOffline().then(setQueueSize);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
 const capturePosition=()=>{if(!navigator.geolocation){setMsg("Geolocation not supported");return}navigator.geolocation.getCurrentPosition(async p=>{const c={lat:p.coords.latitude,lon:p.coords.longitude};setPos(c);try{const {data}=await api.get("/gis/nearby",{params:c});setNearest(data)}catch{}},()=>setMsg("Could not read GPS"),{enableHighAccuracy:true,timeout:8000})};
 const submit=async()=>{if(!pos){setMsg("Capture GPS first.");return}setSubmitting(true);const client_uuid=crypto.randomUUID();const payload={lat:pos.lat,lon:pos.lon,report_type:type,description,reporter_role:"FIELD_OFFICER",client_uuid};try{if(online){const {data}=await api.post("/reports",payload);const {data:sessionData}=await auth.session();if(photo&&sessionData.session?.user?.id&&data.id)await uploadReportDataUrl(photo,sessionData.session.user.id,data.id,photoName);setMsg("Report submitted with evidence.")}else{enqueueOffline({...payload,photo_data_url:photo,photo_file_name:photoName});setQueueSize(getOfflineQueue().length);setMsg("Offline — queued locally. Will sync when online.")}setDescription("");setPhoto(null);setPhotoName("evidence.jpg")}catch(e){enqueueOffline({...payload,photo_data_url:photo,photo_file_name:photoName});setQueueSize(getOfflineQueue().length);setMsg("Server error — queued locally.")}finally{setSubmitting(false)}};
 const onPhoto=e=>{const f=e.target.files?.[0];if(!f)return;setPhotoName(f.name);const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(f)};
 const flushNow=async()=>{const left=await flushOffline();setQueueSize(left)};
 return <div className="min-h-screen bg-[var(--bg)] pb-24" data-testid="field-page"><header className="sticky top-0 z-10 bg-[var(--bg)] border-b border-[var(--border)] px-4 py-3 flex items-center gap-3"><button onClick={()=>nav("/login")} data-testid="back-login" className="text-[var(--text-2)]"><ArrowLeft size={18}/></button><div><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)]">Field Officer</div><div className="font-heading font-bold text-lg tracking-tighter">On-ground reporting</div></div><div className="ml-auto flex items-center gap-2"><span className={`chip ${online?"sev-low":"sev-critical"}`} data-testid="net-status">{online?<WifiHigh size={11}/>:<WifiSlash size={11}/>} {online?"Online":"Offline"}</span>{queueSize>0&&<button onClick={flushNow} data-testid="flush-btn" className="chip sev-medium"><CloudArrowUp size={11}/> {queueSize} pending</button>}</div></header>
 <div className="p-4 space-y-4 max-w-md mx-auto"><div className="tactical-card p-4"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2">Step 1 · Capture GPS</div><button onClick={capturePosition} data-testid="gps-btn" className="w-full py-3 tactical-border bg-white/[0.03] font-mono uppercase tracking-[0.15em] text-sm hover:bg-white/[0.06] flex items-center justify-center gap-2"><MapPin size={16}/> Get current location</button>{pos&&<div className="mt-2 font-mono text-xs" data-testid="gps-value"><div>Lat: {pos.lat.toFixed(5)} · Lon: {pos.lon.toFixed(5)}</div>{nearest&&<div className="mt-1 text-[var(--text-2)]">Nearest road: {nearest.roads?.[0]?.name} ({nearest.roads?.[0]?.status}, {nearest.roads?.[0]?.distance_km} km)</div>}</div>}</div><div className="tactical-card p-4"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2">Step 2 · Report type</div><div className="grid grid-cols-2 gap-2">{TYPES.map(t=><button key={t} data-testid={`type-${t}`} onClick={()=>setType(t)} className={`py-2 text-xs font-mono uppercase tracking-[0.1em] tactical-border ${type===t?"bg-[var(--sev-critical)] text-white border-[var(--sev-critical)]":"hover:bg-white/5"}`}>{t.replaceAll("_"," ")}</button>)}</div></div><div className="tactical-card p-4"><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] mb-2">Step 3 · Description + photo</div><textarea data-testid="desc-input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what you see…" rows={3} className="w-full tactical-border bg-transparent p-2 text-sm font-body focus:outline-none focus:border-white"/><label className="mt-2 inline-flex items-center gap-2 tactical-border px-3 py-2 text-xs font-mono uppercase tracking-[0.15em] cursor-pointer hover:bg-white/5"><Camera size={12}/> {photo?"Photo attached":"Attach photo"}<input data-testid="photo-input" type="file" accept="image/*" capture="environment" onChange={onPhoto} className="hidden"/></label></div><button onClick={submit} disabled={submitting} data-testid="submit-btn" className="w-full py-3 bg-[var(--sev-critical)] text-white font-mono uppercase tracking-[0.15em] text-sm hover:bg-red-500 disabled:opacity-50">{submitting?"Submitting…":online?"Submit report":"Queue offline"}</button>{msg&&<div className="font-mono text-xs text-center text-[var(--text-2)]" data-testid="submit-msg">{msg}</div>}<Link to="/dashboard" className="block text-center font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--text-2)] hover:text-white">← Ops console</Link></div></div>;
}
