-- Allow the trusted backend service role to execute GIS-backed RPCs.
-- Public clients never use this role directly.
GRANT USAGE ON SCHEMA gis TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gis TO service_role;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA gis TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA gis TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA gis
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA gis
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA gis
  GRANT EXECUTE ON FUNCTIONS TO service_role;
