DROP POLICY IF EXISTS alerts_authority_write ON public.alerts;
CREATE POLICY alerts_authority_insert ON public.alerts FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
CREATE POLICY alerts_authority_update ON public.alerts FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
CREATE POLICY alerts_authority_delete ON public.alerts FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
DROP POLICY IF EXISTS feedback_read_authority ON public.model_feedback;
DROP POLICY IF EXISTS response_tasks_authority_write ON public.response_tasks;
CREATE POLICY response_tasks_authority_insert ON public.response_tasks FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY response_tasks_update ON public.response_tasks FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY') OR (SELECT auth.uid()) = assigned_to) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY') OR (SELECT auth.uid()) = assigned_to);
CREATE POLICY response_tasks_authority_delete ON public.response_tasks FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
DROP POLICY IF EXISTS predictions_authority_write ON public.risk_predictions;
CREATE POLICY predictions_authority_insert ON public.risk_predictions FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
CREATE POLICY predictions_authority_update ON public.risk_predictions FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
CREATE POLICY predictions_authority_delete ON public.risk_predictions FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
DROP POLICY IF EXISTS roads_authority_write ON public.roads;
CREATE POLICY roads_authority_insert ON public.roads FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY roads_authority_update ON public.roads FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY roads_authority_delete ON public.roads FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
DROP POLICY IF EXISTS sensors_authority_write ON public.sensors;
CREATE POLICY sensors_authority_insert ON public.sensors FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY sensors_authority_update ON public.sensors FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY sensors_authority_delete ON public.sensors FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
DROP POLICY IF EXISTS zones_authority_write ON public.zones;
CREATE POLICY zones_authority_insert ON public.zones FOR INSERT TO authenticated WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY zones_authority_update ON public.zones FOR UPDATE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
CREATE POLICY zones_authority_delete ON public.zones FOR DELETE TO authenticated USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY'));
ALTER POLICY reports_authority_update ON public.reports USING ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER')) WITH CHECK ((SELECT public.current_user_role()) IN ('ADMIN','AUTHORITY','FIELD_OFFICER'));
CREATE INDEX IF NOT EXISTS reports_nearest_zone_id_idx ON public.reports(nearest_zone_id);
